/**
 * * Actions for authentication
 */
export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

/**
 * * Actions for school
 */

export const SCHOOLS_FETCH_ONE_SUCCESS = "SCHOOLS_FETCH_ONE_SUCCESS";
export const SCHOOLS_FETCH_SUCCESS = "SCHOOLS_FETCH_SUCCESS";
export const SCHOOLS_FETCH_LOADING = "SCHOOLS_FETCH_LOADING";
export const SCHOOLS_CREATE_SUCCESS = "SCHOOLS_CREATE_SUCCESS";
export const SCHOOLS_UPDATE_SUCCESS = "SCHOOLS_UPDATE_SUCCESS";
export const SCHOOLS_DELETE_SUCCESS = "SCHOOLS_DELETE_SUCCESS";

export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";
